name: k6-performance-test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  k6-load-test:
    runs-on: ubuntu-latest

    env:
      TARGET_URL: https://test.k6.io
      ENVIRONMENT: ci
      # InfluxDB for k6 -> Grafana
      K6_OUT: influxdb=${{ secrets.INFLUXDB_URL }}/k6

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 performance test
        run: |
          k6 run k6-script.js

      - name: Download Allure CLI
        run: |
          wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.0/allure-commandline-2.24.0.zip -O allure.zip
          unzip allure.zip -d allure-cli
          echo "${{ github.workspace }}/allure-cli/allure-2.24.0/bin" >> $GITHUB_PATH

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Publish Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
